packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@clerk/expo": ^3.7.0
  "@clerk/nextjs": ^7.5.13
  "@eslint/js": ^9.38.0
  "@tailwindcss/postcss": ^4.1.16
  "@types/node": ^22.18.12
  convex: ^1.42.1
  eslint: ^9.38.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  react19:
    "@types/react": ~19.2.0
    "@types/react-dom": ~19.2.0
    react: 19.2.0
    react-dom: 19.2.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
