#!/usr/bin/env node
/**
 * Regenerates both platform outputs from the hand-edited sources in `src/`:
 *
 *   tooling/tailwind/theme.css     oklch, for Tailwind
 *   src/__generated__/native.ts    hex + RN shadow objects, for React Native
 *
 * Run with `pnpm tokens:build`. Both outputs are committed so a clean clone
 * builds without running codegen first.
 */

import { execFile } from "node:child_process";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

import type {
  ColorScheme,
  ColorToken,
  RadiusToken,
  ShadowToken,
} from "../src/contracts.ts";
import type { ShadowLayer } from "../src/scale.ts";

import { colors } from "../src/palette.ts";
import {
  radius,
  radiusBase,
  shadows,
  spacingUnit,
  trackingNormal,
} from "../src/scale.ts";
import { oklchToHex } from "./oklch.ts";

const ROOT = path.join(import.meta.dirname, "../../..");
const CSS_OUT = path.join(ROOT, "tooling/tailwind/theme.css");
const NATIVE_OUT = path.join(
  import.meta.dirname,
  "../src/__generated__/native.ts",
);

const SCHEMES: ColorScheme[] = ["light", "dark"];
const COLOR_TOKENS = Object.keys(colors.light) as ColorToken[];
const RADIUS_TOKENS = Object.keys(radius) as RadiusToken[];
const SHADOW_TOKENS = Object.keys(shadows.light) as ShadowToken[];

const TRACKING_STEPS = {
  tighter: -0.05,
  tight: -0.025,
  normal: 0,
  wide: 0.025,
  wider: 0.05,
  widest: 0.1,
};

/** `cardForeground` → `card-foreground`, `chart1` → `chart-1`. */
const kebab = (name: string): string =>
  name
    .replace(/([A-Z])/g, (upper) => `-${upper.toLowerCase()}`)
    .replace(/(\d+)$/, "-$1");

const rem = (px: number): string => `${px / 16}rem`;

/** `--shadow` has no suffix; every other step does. */
const shadowVar = (token: ShadowToken): string =>
  token === "DEFAULT" ? "--shadow" : `--shadow-${token}`;

const cssShadow = (layers: ShadowLayer[]): string =>
  layers
    .map(
      (l) =>
        `${l.x}px ${l.y}px ${l.blur}px ${l.spread}px hsl(0 0% 0% / ${l.alpha})`,
    )
    .join(", ");

const cssRadius = (token: RadiusToken): string => {
  const delta = radius[token] - radiusBase;
  if (delta === 0) return "var(--radius)";
  return `calc(var(--radius) ${delta > 0 ? "+" : "-"} ${Math.abs(delta)}px)`;
};

const schemeBlock = (scheme: ColorScheme, indent: string): string =>
  [
    ...COLOR_TOKENS.map(
      (token) => `${indent}--${kebab(token)}: ${colors[scheme][token]};`,
    ),
    `${indent}--radius: ${rem(radiusBase)};`,
    ...SHADOW_TOKENS.map(
      (token) =>
        `${indent}${shadowVar(token)}: ${cssShadow(shadows[scheme][token])};`,
    ),
  ].join("\n");

const buildCss =
  (): string => `/* Generated by \`pnpm tokens:build\` from packages/tokens/src — do not edit. */

:root {
${schemeBlock("light", "  ")}
  --tracking-normal: ${rem(trackingNormal)};
  --spacing: ${rem(spacingUnit)};

  @variant dark {
${schemeBlock("dark", "    ")}
  }
}

@theme inline {
${COLOR_TOKENS.map((t) => `  --color-${kebab(t)}: var(--${kebab(t)});`).join("\n")}

  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);

${RADIUS_TOKENS.map((t) => `  --radius-${t}: ${cssRadius(t)};`).join("\n")}

${SHADOW_TOKENS.map((t) => `  ${shadowVar(t)}: var(${shadowVar(t)});`).join("\n")}

${Object.entries(TRACKING_STEPS)
  .map(([name, em]) =>
    em === 0
      ? `  --tracking-${name}: var(--tracking-normal);`
      : `  --tracking-${name}: calc(var(--tracking-normal) ${em > 0 ? "+" : "-"} ${Math.abs(em)}em);`,
  )
  .join("\n")}
}
`;

const nativeShadow = (layers: ShadowLayer[]): string =>
  `[${layers
    .map(
      (l) =>
        `{ offsetX: ${l.x}, offsetY: ${l.y}, blurRadius: ${l.blur}, spreadDistance: ${l.spread}, color: "rgba(0, 0, 0, ${l.alpha})" }`,
    )
    .join(", ")}]`;

const buildNative =
  (): string => `/* Generated by \`pnpm tokens:build\` from packages/tokens/src — do not edit. */

import type {
  ColorScheme,
  ColorToken,
  HexColor,
  NativeShadow,
  ShadowToken,
} from "../contracts";

export const nativeColors: Record<
  ColorScheme,
  Record<ColorToken, HexColor>
> = {
${SCHEMES.map(
  (scheme) => `  ${scheme}: {
${COLOR_TOKENS.map((t) => `    ${t}: "${oklchToHex(colors[scheme][t])}",`).join("\n")}
  },`,
).join("\n")}
};

export const nativeShadows: Record<
  ColorScheme,
  Record<ShadowToken, NativeShadow[]>
> = {
${SCHEMES.map(
  (scheme) => `  ${scheme}: {
${SHADOW_TOKENS.map((t) => `    "${t}": ${nativeShadow(shadows[scheme][t])},`).join("\n")}
  },`,
).join("\n")}
};
`;

await writeFile(CSS_OUT, buildCss(), "utf8");
await writeFile(NATIVE_OUT, buildNative(), "utf8");

// Formatting here rather than emitting oxfmt-shaped strings keeps the
// templates above readable, and stops `pnpm format --check` failing right
// after a regeneration.
await promisify(execFile)("pnpm", ["exec", "oxfmt", CSS_OUT, NATIVE_OUT], {
  cwd: ROOT,
});

console.log(`✓ ${path.relative(ROOT, CSS_OUT)}`);
console.log(`✓ ${path.relative(ROOT, NATIVE_OUT)}`);
